# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

variables:
  projectFolder: '/src/Cyclix.Client.UI'
  buildOutputFolder: '/src/Cyclix.Client.UI/dist/cyclix-app'
trigger:
- main

pool:
  vmImage: ubuntu-latest
steps:
- task: NodeTool@0
  inputs:
    versionSpec: '18.x'
  displayName: 'Install Node.js'
- script: |
    npm install 
  displayName: 'npm install '
- task: Npm@1
  displayName: 'npm install'
  inputs:
    workingDir: '$(System.DefaultWorkingDirectory)/$(projectFolder)'
    verbose: false

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      pwd
      ls -l
      ls -l dist/
- task: AzureStaticWebApp@0
  displayName: 'Deploy Azure static webapp'
  inputs:
    app_location: '$(System.DefaultWorkingDirectory)/$(projectFolder)'
    output_location: '$(System.DefaultWorkingDirectory)/$(buildOutputFolder)' 
  env:
    azure_static_web_apps_api_token: $(deployment_token)
