# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

variables:
  projectFolder: '/src/DriveNow.Client.UI'
  buildOutputFolder: '/src/DriveNow.Client.UI/dist/car-rent'
trigger:
- main

pool:
  vmImage: ubuntu-latest
steps:
- task: NodeTool@0
  inputs:
    versionSpec: '18.x'
  displayName: 'Install Node.js'

- task: Npm@1  
  displayName: 'Angular CLI latest'  
  inputs:  
    command: custom  
    verbose: false  
    customCommand: 'install -g @angular/cli'

- task: CmdLine@2
  displayName: 'yarn install install and build'
  inputs:
    script: |
      yarn install --immutable --immutable-cache --check-cache
      ng build --configuration production --aot --optimization=true --build-optimizer=true --source-map=false
    workingDirectory: '$(System.DefaultWorkingDirectory)/$(projectFolder)'

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      pwd
      ls -l
      ls -l dist/
- task: AzureStaticWebApp@0
  displayName: 'Deploy Azure static webapp'
  inputs:
    app_location: '$(System.DefaultWorkingDirectory)/$(projectFolder)'
    output_location: '$(System.DefaultWorkingDirectory)/$(buildOutputFolder)' 
  env:
    azure_static_web_apps_api_token: $(deployment_token)
