# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger: none
pool:
  vmImage: ubuntu-latest
steps:
- task: NodeTool@0
  inputs:
    versionSpec: '18.x'
  displayName: 'Install Node.js'
- script: |
    npm install -g @angular/cli
  displayName: 'install angular cli'
- task: AngularCLI@1
  inputs:
    command: 'build'
    project: 'src/DriveNow.Client.UI'
    prod: false
    DisableAnalytics: false
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      pwd
      ls -l
      ls -l dist/
- task: AzureStaticWebApp@0
  displayName: 'Deploy Azure static webapp'
  inputs:
    app_location: '/src/DriveNow.Client.UI'
    output_location: '/src/DriveNow.Client.UI/dist/car-rent'
  env:
    azure_static_web_apps_api_token: $(deployment_token)
