# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

variables:
  projectFolder: '/src/DriveNow.Client.UI'
  buildOutputFolder: '/src/DriveNow.Client.UI/dist/car-rent'
trigger:
- main
pool:
      vmImage: 'ubuntu-latest'

steps:
    
      - task: NodeTool@0
        inputs:
          versionSource: 'spec'
          versionSpec: '18.x'
      - task: Npm@1
        inputs:
          command: 'install'
      - task: AngularCLI@1
        inputs:
          command: 'build'
          prod: false
          DisableAnalytics: false

      - task: ArchiveFiles@2
        displayName: 'Archive files'
        inputs:
          rootFolderOrFile: '$(System.DefaultWorkingDirectory)/src/DriveNow.Client.UI/dist/angular-with-azure/'
          includeRootFolder: false
          archiveType: zip
          archiveFile: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
          replaceExistingArchive: true

      - task: PublishBuildArtifacts@1
        inputs:
          PathtoPublish: '$(Build.ArtifactStagingDirectory)/src/DriveNow.Client.UI/$(Build.BuildId).zip'
          ArtifactName: 'drop'
          publishLocation: 'Container'
