# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

variables:
  projectFolder: '/src/DriveNow.Client.UI'
  buildOutputFolder: '/src/DriveNow.Client.UI/dist/car-rent'
trigger:
- main
pool:
      vmImage: 'ubuntu-latest'

steps:
    
      - task: NodeTool@0
        inputs:
          versionSpec: '18.x'
        displayName: 'Install Node.js 16.x'

      - script: |
          cd AngularWithAzure/
          npm install -g @angular/cli
          npm install
          ng build --prod
        displayName: 'npm install and build'
        workingDirectory: '$(Build.SourcesDirectory)/src/DriveNow.Client.UI'
      - task: CmdLine@2
        displayName: "Run unit tests"
        inputs:
          script: |
            cd AngularWithAzure/
            ng test --browsers=ChromeHeadless --code-coverage --watch=false
      - task: ArchiveFiles@2
        displayName: 'Archive files'
        inputs:
          rootFolderOrFile: '$(System.DefaultWorkingDirectory)/src/DriveNow.Client.UI/dist/angular-with-azure/'
          includeRootFolder: false
          archiveType: zip
          archiveFile: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
          replaceExistingArchive: true

      - task: PublishBuildArtifacts@1
        inputs:
          PathtoPublish: '$(Build.ArtifactStagingDirectory)/src/DriveNow.Client.UI/$(Build.BuildId).zip'
          ArtifactName: 'drop'
          publishLocation: 'Container'
